openapi: 3.0.0
paths:
  /users:
    get:
      tags:
        - Users
      summary: 'Get list of users'
      description: 'Returns list of users'
      operationId: getUsersList
      responses:
        '200':
          description: 'Successful operation'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserListResource'
  '/users{user}':
    get:
      operationId: 8c72d9a9a5dce4c3e4d320a471e80c58
      parameters:
        -
          name: user
          in: path
          description: 'ID de la resource'
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: 'Successful operation'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserListResource'
        '404':
          description: 'Not found'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserListResource'
components:
  schemas:
    UserListResource:
      title: UserListResource
      description: 'User resource'
      properties:
        data:
          title: Data
          description: 'Data wrapper'
          type: array
          items:
            properties:
              id:
                description: ID
                type: integer
              firstname:
                description: 'First Name'
                type: string
              lastname:
                description: 'Last Name'
                type: string
              fullname:
                description: 'Full Name'
                type: string
              email:
                description: Email
                type: string
                format: email
              phone_number:
                description: 'Phone Number'
                type: string
              roles:
                description: Roles
                type: array
                items:
                  type: string
              avatar:
                description: 'Avatar URL'
                type: string
              created_at:
                description: 'Created At'
                type: string
                format: date-time
            type: object
      type: object
      xml:
        name: UserListResource
tags:
  -
    name: Users
    description: Users
